### ISSUE TITLE
does not build with ghc 8.4.2

### ISSUE THREAD

**Issue by shapr** [supki/libjenkins#1]
```src/Jenkins/Rest/Internal.hs:45:32: error:
    Module ‘Data.Conduit’ does not export ‘ResumableSource’
   |
45 | import           Data.Conduit (ResumableSource)
   |  ```

I had a need for this today, but it hasn't kept up with conduit.
I'm not familiar with conduit, is this an easy fix?

**Comment by shapr** [comment]
A quick dig through conduit docs shows 1.3.0 is the first version that doesn't have `ResumableSource`

I constrained conduit to < 1.3.0, but that gives a different error
```
src/Jenkins/Rest/Internal.hs:196:3: error:
    • Couldn't match type ‘conduit-1.2.13.1:Data.Conduit.Internal.Conduit.ConduitM
                             i0 ByteString m ()’
                     with ‘ResumableSource m ByteString’
      Expected type: Http.Manager -> m (ResumableSource m ByteString)
        Actual type: Http.Manager
                     -> m (conduit-1.2.13.1:Data.Conduit.Internal.Conduit.ConduitM
                             i0 ByteString m ())
    • In the expression:
        wrapException . fmap Http.responseBody . Http.http req
      In an equation for ‘streamReq’:
          streamReq req
            = wrapException . fmap Http.responseBody . Http.http req
    • Relevant bindings include
        streamReq :: Request
                     -> Http.Manager -> m (ResumableSource m ByteString)
          (bound at src/Jenkins/Rest/Internal.hs:195:1)
    |
196 |   wrapException . fmap Http.responseBody . Http.http req

```
